{{- include "sch.config.init" (list . "apps.sch.chart.config.values") -}}
{{- if not .Values.systemUser.credsSecretName }}
---
###############################################################################
# Copyright 2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-system-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sch.metadata.labels.standard" (list . "") | nindent 4 }}
data:
  SYSTEM_USER: {{ required "System username is required (systemUser.username)." .Values.systemUser.username | b64enc}}
  SYSTEM_PASSWORD: {{ required "XOR-encrypted password for system user is required (systemUser.password)." .Values.systemUser.password | b64enc }}
{{- end }}
